
[general]
	#Range: 1 ~ 9
	maxCompressionLevel = 9

[blocks]
	enableandesite_alloyBlock = true
	enableasurineBlock = true
	enablebrassBlock = true
	enablecrimsiteBlock = true
	enableexperienceBlock = true
	enablelimestoneBlock = true
	enableochrumBlock = true
	enablescorchiaBlock = true
	enablescoriaBlock = true
	enableveridiumBlock = true
	enablezincBlock = true
	enablenether_starBlock = true
	enableacacia_logBlock = true
	enableacacia_plankBlock = true
	enableamethystBlock = true
	enableandesiteBlock = true
	enablebasaltBlock = true
	enablebirch_logBlock = true
	enablebirch_plankBlock = true
	enableblackstoneBlock = true
	enablebone_blockBlock = true
	enableclayBlock = true
	enablecoalBlock = true
	enablecobbled_deepslateBlock = true
	enablecobblestoneBlock = true
	enablecopperBlock = true
	enablecrimson_stemBlock = true
	enablecrimson_plankBlock = true
	enabledark_oak_logBlock = true
	enabledark_oak_plankBlock = true
	enabledeepslateBlock = true
	enablediamondBlock = true
	enabledioriteBlock = true
	enabledirtBlock = true
	enableemeraldBlock = true
	enableend_stoneBlock = true
	enableglassBlock = true
	enableglowstoneBlock = true
	enablegoldBlock = true
	enablegraniteBlock = true
	enablegrassBlock = true
	enablegravelBlock = true
	enablehayBlock = true
	enablehoneyBlock = true
	enableironBlock = true
	enablejungle_logBlock = true
	enablejungle_plankBlock = true
	enablelapisBlock = true
	enablemelonBlock = true
	enablenetheriteBlock = true
	enablenetherrackBlock = true
	enableoak_logBlock = true
	enableoak_plankBlock = true
	enableobsidianBlock = true
	enablepodzolBlock = true
	enablepumpkinBlock = true
	enablequartzBlock = true
	enableraw_copperBlock = true
	enableraw_goldBlock = true
	enableraw_ironBlock = true
	enablered_sandBlock = true
	enableredstoneBlock = true
	enablesandBlock = true
	enablesnowBlock = true
	enablesoul_sandBlock = true
	enablesoul_soilBlock = true
	enablespruce_logBlock = true
	enablespruce_plankBlock = true
	enablestoneBlock = true
	enableterracottaBlock = true
	enabletuffBlock = true
	enablewarped_stemBlock = true
	enablewarped_plankBlock = true
	enableNetherStarBlock = true
	enableRefinedRadianceBlock = true
	enableShadowSteelBlock = true

