#Base rpm creatures can spin the horse crank.
#Range: > 1
creatureRPMRange = 4
#How much stress small creatures can produce for the horse crank.
#Range: > 1
smallCreatureStressRange = 128
#How much stress medium creatures can produce for the horse crank.
#Range: > 1
mediumCreatureStressRange = 256
#How much stress large creatures can produce for the horse crank.
#Range: > 1
largeCreatureStressRange = 512
#The multiplier for "Poor" paths
#Range: 0.0 ~ 1.7976931348623157E308
poorMultiplier = 0.5
#The multiplier for "Normal" paths
#Range: 0.0 ~ 1.7976931348623157E308
normalMultiplier = 1.0
#The multiplier for "Great" paths
#Range: 0.0 ~ 1.7976931348623157E308
greatMultiplier = 2.0
#Types of blocks valid as "Poor" quality
poorPathBlock = ["minecraft:dirt", "minecraft:grass_block"]
#Types of blocks valid as "Normal" quality
normalPathBlock = ["minecraft:dirt_path", "minecraft:gravel"]
#Types of blocks valid as "Great" quality
greatPathBlock = ["minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice"]
#Valid "Small" creatures
smallCreatures = ["minecraft:wolf"]
#Valid "Medium" creatures
mediumCreatures = ["minecraft:cow"]
#Valid "Large" creatures
largeCreatures = ["minecraft:horse"]

